apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app.kubernetes.io/version: "1.1"
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
        app.kubernetes.io/version: "1.1"
    spec:
      containers:
        - name: myapp
          image: nanajanashia/argocd-app:1.1
          ports:
            - containerPort: 8080
