apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: myapp
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgCG+ZCZWC8ad8c1P3G5tuRfIIHv+thdbJ1fLxRzU8dvC8Ql/WjXArZyf2ANreZXey2vMtBeSSwKOnL2RT9hUj3VwD5RsEtbGMGm3ga60QHO0jubcTGLj8VkZeyiF408ZQtrzhzby8Y/Sdi2cletXU81INtlUdC6MsWDj+93/JxnwUZ5UC+ir2rTTaYD1jFaGeJG7gnb/OAqRsvBu04SslZ9U9bStlB3cNx4ktraevPmU+M+9Hhv5zlCp3mmwzMDftIs7h27Q3sNOpo5CCETFPBK/6vHiFHDwt/em9rofB5P01gHgTEpBmVm7taSE+OOYJ47j2SaIitvW529vWSJj28LD59BX3yqieIJPX6ogYdGcKiSZHGvbNCqqjwjX27eTO5F+pzrPURgNQ+tqKwOp4k2EeE9RTKzwJs84UjLLWHg0/5pOfHhPF4ZMsaDSsiPoVYMeJdxOJjeu535556TSwfVcIW8XsNBPhjDMO7cCe2PaQdUc3A6cApIdXPTGyYfB8I9s6dPAjEyY9u8XBXVxRS2S06AQwo/QH1FqYN3dbIHzqpq5aQIifemNcioOpWL26R+3VYi8gRHHLZJec33d+rrCEc9kSZIThA2RAhc2IG8VuoWtXKpF+QKLaQL5SbPoFpBROB5A/W+1/ZMw3orNf/B/TlviehcqZC+F1mPBcDUMFCjhDKpQTxsX5OgVdVe/nrA+uCi2oSv1eXYszz6SkXFH11rh3HuIcCkqPV6p76FTbyRIpUMx0lz/pVDgS0aidRYwDjr6ZjNiK++zB+aumqhwOgE4mrRIMieJOKCwg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: slack-webhook
      namespace: myapp
    type: Opaque

