apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-oreplay
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oreplay/oreplay-infrastructure.git
    targetRevision: HEAD
    path: k8s/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: oreplay

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
