nginx:
  replicaCount: 1
  image:
    registry: docker.io
    repository: oreplay/frontend
    tag: v0.2.24
  command:
    - /bin/sh
    - -c
    - cd /var/www && npm run preview
  extraEnvVars:
    - name: VITE_VERSION_NUMBER
      value: "v0.2.24"
    - name: VITE_API_DOMAIN
      value: "https://www.oreplay.es/"
    - name: VITE_VERSION_TYPE
      value: "beta"
    - name: VITE_DESKTOP_CLIENT_VERSION_FALLBACK
      value: "0.4.4"
  resources:
    requests:
      cpu: 50m
      memory: 450M
    limits:
      cpu: 600m
      memory: 500M
  containerPorts:
    http: 4173
  service:
    type: NodePort
    nodePorts:
      http: 30002
    targetPort:
      http: 4173
