nginx:
  replicaCount: 1
  image:
    registry: docker.io
    repository: oreplay/frontend
    tag: v0.3.5
  command:
    - /bin/sh
    - -c
    - cd /var/www && npm run preview
  extraEnvVars:
  resources:
    requests:
      cpu: 50m
      memory: 300M
    limits:
      cpu: 400m
      memory: 500M
  containerPorts:
    http: 4173
  service:
    type: NodePort
    nodePorts:
      http: 30002
    targetPort:
      http: 4173
