apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oreplay-api-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: nginx
    targetRevision: 19.1.1
    helm:
      releaseName: nginx-php-api
      valuesFiles:
        - api/api-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: oreplay

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
