apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oreplay-cakeapi-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/oreplay/oreplay-infrastructure.git
    targetRevision: HEAD
    path: k8s/charts/nginx
    helm:
      releaseName: nginx-php-api
      valueFiles:
        - values.yaml
      parameters:
        - name: nginx.replicaCount
          value: "1"
        - name: nginx.customLivenessProbe
          value: null
        - name: nginx.customReadinessProbe
          value: null
  destination:
    server: https://kubernetes.default.svc
    namespace: oreplay

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
