apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oreplay-frontend-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/oreplay/oreplay-infrastructure.git
    targetRevision: HEAD
    path: k8s/charts/nginx
    helm:
      releaseName: nginx-front-react
      valueFiles:
        - values.yaml
        - values-front.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: oreplay

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
