apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oreplay-memcached
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: memcached
    targetRevision: 7.6.3
    helm:
      releaseName: api-memcached
      values: |
        replicaCount: 1
        auth:
          enabled: false
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: oreplay
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
