apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-memcached
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: memcached
    targetRevision: latest
    helm:
      releaseName: api-memcached
      values: |
        replicaCount: 1
        auth:
          enabled: false
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
